env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
  - '@typescript-eslint'
rules:
  react/prop-types: 'off'
  no-console: 'warn'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  'prettier/prettier': 'error'
  react/no-unknown-property:
    - error
    - ignore:
        - intensity
        - position
        - args
        - geometry
        - material
        - '^Canvas.*'
        - '^THREE.*'
settings:
  react:
    version: 'detect'
